{{- if .Values.ingress.clusterApi.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-cluster-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.ingress.clusterApi.proxyBodySize }}"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
      - {{ .Values.ingress.clusterApi.host }}
    secretName: {{ .Values.ingress.clusterApi.secretName }}
  rules:
  - host: {{ .Values.ingress.clusterApi.host }}
    http:
      paths:
      - path: /(.+)
        pathType: Prefix
        backend:
          service:
            name: {{ include "ipfs-cluster.serviceNameLocal" . }}
            port: 
              name: api-http
{{- end }}
