{{- if .Values.ingress.gateway.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
      - {{ .Values.ingress.gateway.host }}
    secretName: {{ .Values.ingress.gateway.secretName }}
  rules:
  - host: {{ .Values.ingress.gateway.host }}
    http:
      paths:
      - path: /(.+)
        pathType: Prefix
        backend:
          service:
            name: {{ include "ipfs-cluster.serviceNameHttp" . }}
            port: 
              name: gateway
{{- end }}
