{{- if .Values.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-rules
  labels:
      app: {{ .Values.monitor.app }}
      app.kubernetes.io/name: {{ .Release.Name }}
      component: ipfs-cluster
      release: {{ .Values.monitor.release }}
spec:
  groups:
    - name: {{ .Release.Name }}.rules
      rules:
      - alert: IpfsClusterPinsPinError
        annotations:
          message: 'Ipfs cluster pins pin error  (pod {{`{{`}} $labels.pod {{`}}`}}, job {{`{{`}} $labels.job {{`}}`}}) > {{ .Values.monitor.alert.pinsPinErrorThreshold }}, VALUE = {{`{{`}} $value {{`}}`}}'
        expr: max by(job, pod)(ipfscluster_pins_pin_error{job="{{ .Release.Namespace }}/{{ .Release.Name }}"}) > {{ .Values.monitor.alert.pinsPinErrorThreshold }}
        for: 5m
        labels:
          severity: warning
      - alert: IpfsClusterPinsPinQueuedTooLarge
        annotations:
          message: 'Ipfs cluster pins pin queued  (pod {{`{{`}} $labels.pod {{`}}`}}, job {{`{{`}} $labels.job {{`}}`}}) > {{ .Values.monitor.alert.pinsPinQueuedThreshold }}, VALUE = {{`{{`}} $value {{`}}`}}'
        expr: max by(job, pod)(ipfscluster_pins_pin_queued{job="{{ .Release.Namespace }}/{{ .Release.Name }}"}) > {{ .Values.monitor.alert.pinsPinQueuedThreshold }}
        for: 5m
        labels:
          severity: warning
      - alert: IpfsClusterPinsPinningTooLarge
        annotations:
          message: 'Ipfs cluster pins pin queued  (pod {{`{{`}} $labels.pod {{`}}`}}, job {{`{{`}} $labels.job {{`}}`}}) > {{ .Values.monitor.alert.pinsPinningThreshold }}, VALUE = {{`{{`}} $value {{`}}`}}'
        expr: max by(job, pod)(ipfscluster_pins_pinning{job="{{ .Release.Namespace }}/{{ .Release.Name }}"}) > {{ .Values.monitor.alert.pinsPinningThreshold }}
        for: 5m
        labels:
          severity: warning
{{- end }}

