# Exposed
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs-cluster.serviceName" . }}
  labels:
    node: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - name: swarm
    targetPort: swarm
    port: 4001
  - name: swarm-udp
    targetPort: swarm-udp
    port: 4002 
  - name: cluster-swarm
    targetPort: cluster-swarm
    port: 9096 # ipfs cluster bootstrap port
  - name: restapi-swarm
    targetPort: restapi-swarm
    port: 9098 # client add peer port
  {{- with .Values.serviceExternalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}
---
# Exposed behind Proxy
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs-cluster.serviceNameHttp" . }}
  labels:
    node: {{ .Release.Name }}
spec:
  ports:
  - name: gateway
    targetPort: gateway
    port: 8080  
  selector:
    app: {{ .Release.Name }} 
---
# Not Exposed
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs-cluster.serviceNameLocal" . }}
  labels:
    node: {{ .Release.Name }}
spec:
  ports:
  - name: api
    targetPort: api
    port: 5001 
  - name: proxy-http
    targetPort: proxy-http
    port: 9095 
  - name: ws
    targetPort: ws
    port: 8081 
  - name: api-http
    targetPort: api-http
    port: 9094    
  selector:
    app: {{ .Release.Name }}      
---
# Ipfs Cluster Swarm headless
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs-cluster.serviceName" . }}-headless
  labels:
    node: {{ .Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: swarm
    targetPort: swarm
    port: 4001
  - name: swarm-udp
    targetPort: swarm-udp
    port: 4002
  - name: cluster-swarm
    targetPort: cluster-swarm
    port: 9096 # ipfs cluster bootstrap port
  - name: restapi-swarm
    targetPort: restapi-swarm
    port: 9098 # client add peer port
  selector:
    app: {{ .Release.Name }}
---
# Ipfs Gateway Headless
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs-cluster.serviceNameHttp" . }}-headless
  labels:
    node: {{ .Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: gateway
    targetPort: gateway
    port: 8080
  selector:
    app: {{ .Release.Name }}
---
# Ipfs Cluster Local Headless
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs-cluster.serviceNameLocal" . }}-headless
  labels:
    node: {{ .Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: api
    targetPort: api
    port: 5001
  - name: proxy-http
    targetPort: proxy-http
    port: 9095
  - name: ws
    targetPort: ws
    port: 8081
  - name: api-http
    targetPort: api-http
    port: 9094
  selector:
    app: {{ .Release.Name }}
