{{- if .Values.additionalNfsPvc }}

{{- $namespace := include "project.namespace" . -}}
{{- $fullname := include "project.fullname" . -}}
{{- $values := .Values -}}

{{- range .Values.additionalNfsPvc }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullname }}-{{ .name }}
  namespace: {{ $namespace }}
  labels:
    application: {{ $fullname }}
    {{- toYaml $values.commonLabels | nindent 4 }}
    {{- if $values.customLabels }}
    {{- toYaml $values.customLabels | nindent 4 }}
    {{- end }}
spec:
  storageClassName: {{ default nfs .storageClassName | quote }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}
